apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
        - name: {{ .Values.storage.pvc.name }}
          persistentVolumeClaim:
           claimName: {{ .Values.storage.pvc.name }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: SSH_AUTHORIZED_KEY
            value: "{{ .Values.ssh.authorized_keys }}"
        ports:
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: {{ .Values.storage.mntPath }}
          name: {{ .Values.storage.pvc.name }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
