# Default values for dev-env.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: quay.io/andrewrothstein/docker-dev-env
  tag: ubuntu_xenial
  pullPolicy: IfNotPresent

persistence:
  mntPath: /root/dev
  enabled: true
  accessMode: ReadWriteOnce
  size: 50Gi

service:
  name: dev-env

ssh:
  authorized_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCYL2GwauvSBcKzbPTca6W2S0MnN6R0+AAe/ZzD7JRQiUukgGHGNTtPTJ3cl8qnKJuWTInMjLltBKTHmbu442xvjGZegoOCh5fuD6oaEVEGJ3OYpN94eq+IUj7E+hGSoB2nnuu4D8DJcv98Ps1nFcnTTcysXpqQKtMxlYJmx/6KZoFWkjRu4koRLnkvskLLigiJKjJbDOU8rtUYEe48TTFc/jkner5aWQk7SD3V8Hv1FCQFtF+sJcY618JxMqCXfTG0x9avK3KdGiz6pZSCUXZ2QZ+hrSpwlPcG2Wir/AkzZdnoHfcg/T9UNL1kUnjckoUeuH5DTMCVedprwepQ0DY4kNF3bksbNtPpd5DAOsF5OLGw5uE5rGvbqb3Dcok8dqmQ+ZhGtlurk8LaIzoTQfjYWA2lXawiXiPa3+5pOPsepjawgoewpA6alyjswTUk9py655bFdUqI7GXb8vYshHlEL6PUr+2vyJwJLyTNKAw67HsMCaLSUVQKw08nMUzt50EFFgnuRlv5QuIKfBeUwKL7dk5AxnfVpMoCl67mewaEhOEiNDzh917vUoSyc5VGiEY5WGCbftFEf6TsDcFGnkxb4c/hN81nk0AGyC04iFtOWni3Q7dMoPuJr6YXdFphXzdNX5+O6ggjpSz62zJUZ5QI8yW3vzkTxkwHsrzfA0LsIQ== air@AIR-PSNY-GU1

resources:
  limits:
    cpu: 4
    memory: 8192Mi
  requests:
    cpu: 2
    memory: 4096Mi
